config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "homes#top"
  resources :microposts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
  	resources :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :user
	belongs_to :micropost
end

app/models/micropost.rb
class Micropost < ApplicationRecord
	belongs_to :user
	has_many :likes, dependent: :destroy
	def liked_by?(user)
		likes.where(user_id: user.id).exists?
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :microposts, dependent: :destroy
  has_many :likes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	before_action :configure_permitted_parameters, if: :devise_controller?

	def after_sign_in_path_for(resource)
		root_path
	end

	def after_sign_out_path_for(resource)
		root_path
	end

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def top
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
	def create
		micropost = Micropost.find(params[:micropost_id])
		like = current_user.likes.new(micropost_id: micropost.id)
		like.save
		redirect_to micropost_path(micropost)
	end

	def destroy
		micropost = Micropost.find(params[:micropost_id])
		like = current_user.likes.find_by(micropost_id: micropost.id)
		like.destroy
		redirect_to micropost_path(micropost)
	end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	def new
		@micropost = Micropost.new
	end

	def create
		@micropost = Micropost.new(micropost_params)
		@micropost.user = current_user
		if @micropost.save
			redirect_to micropost_path(@micropost)
		else
			render 'new'
		end
	end

	def index
		@microposts = Micropost.all
	end

	def show
		@micropost = Micropost.find(params[:id])
	end

	def edit
		@micropost = Micropost.find(params[:id])
	end

	def update
		@micropost = Micropost.find(params[:id])
		@micropost.user = current_user
		if @micropost.update(micropost_params)
			redirect_to micropost_path(@micropost)
		else
			render 'edit'
		end
	end

	def destroy
		@micropost = Micropost.find(params[:id])
		@micropost.destroy
		redirect_to microposts_path
	end

	private
	def micropost_params
		params.require(:micropost).permit(:title, :body, :user_id)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<h1>markへようこそ</h1>

<%= link_to "投稿する", new_micropost_path %>
<%= link_to "投稿一覧", microposts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mark</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" >
    <link rel="stylesheet" href="style.css">
  </head>

  <body>
    <% if user_signed_in? %>
      <%= link_to "MARK", root_path %>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <p>ようこそ<%= current_user.name %>さん</p>
    <% else %>
      <%= link_to "MARK", root_path %>
      <%= link_to "新規登録", new_user_registration_path %>
      <%= link_to "ログイン", new_user_session_path %>
      <p>ようこそゲストさん</p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/microposts/edit.html.erb
<h1>編集</h1>

<%= form_for(@micropost) do |f| %>
	<div class="field">
		<%= f.label :タイトル %><br />
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :本文 %><br />
		<%= f.text_area :body %>
	</div>

	<div class="field">
		<%= f.submit "編集内容を保存" %>
	</div>
<% end %>

app/views/microposts/index.html.erb
<h1>投稿一覧</h1>

<% @microposts.each do |m| %>
	<div class = "field">
		<%= link_to m.title, micropost_path(m) %>
	</div>
<% end %>

app/views/microposts/new.html.erb
<h1>投稿</h1>

<%= form_for(@micropost) do |f| %>
	<div class="field">
		<%= f.label :タイトル %><br />
		<%= f.text_field :title %>
	</div>

	<div class="field">
		<%= f.label :本文 %><br />
		<%= f.text_area :body %>
	</div>

	<div class="field">
		<%= f.submit "投稿する" %>
	</div>
<% end %>

app/views/microposts/show.html.erb
<h1><%= @micropost.title %></h1>

<%= @micropost.body %>

<% if @micropost.liked_by?(current_user) %>
	<li>
		<%= link_to micropost_like_path(@micropost), method: :delete do %>
	    	<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
	    	<%= @micropost.likes.count %> いいね
	    <% end %>
	</li>
<% else %>
	<li>
	    <%= link_to micropost_likes_path(@micropost), method: :post do %>
	    	<i class="far fa-heart" aria-hidden="true"></i>
	    	<%= @micropost.likes.count %> いいね
	    <% end %>
	</li>
<% end %>

<%= link_to "編集する", edit_micropost_path(@micropost) %>
<%= link_to "削除する", micropost_path(@micropost), method: :delete, "data-confirm" => "本当に削除しますか？" %>